/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;

/**
 *
 * @author rodri
 */
public class jpCards extends javax.swing.JPanel {

  public class CardsPanel extends JPanel {
        public CardsPanel(List<String> nombreSucursal) {
            setLayout(new GridLayout(0, 3, 10, 10)); // 3 columnas de cards

            for (String nombre : nombreSucursal) {
                JPanel card = crearCard(nombre);
                add(card);
            }
        }

        private JPanel crearCard(String nombreSucursal) {
            JPanel card = new JPanel();
            card.setLayout(new BorderLayout());
            card.setBorder(BorderFactory.createLineBorder(Color.BLACK));

            JLabel nombreLabel = new JLabel(nombreSucursal, SwingConstants.CENTER);
            card.add(nombreLabel, BorderLayout.CENTER);
            return card;
        }
    }
    /**
     * Creates new form jpCards
     */
    public jpCards(List<String> nombre) {
        initComponents();

        if (nombre == null || nombre.isEmpty()) {
            System.out.println("Error: La lista de nombres está vacía.");
        } else {
            System.out.println("Se han cargado los siguientes nombres: " + nombre);
        }

        CardsPanel cardsPanel = new CardsPanel(nombre);
        this.setLayout(new BorderLayout());  
        this.add(cardsPanel, BorderLayout.CENTER);  

        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

 public static void main(String[] args) {
        Sucursal Sucursal = new Sucursal();
        List<String> nombre = Sucursal.obtenerDatos();

        if (nombre == null || nombre.isEmpty()) {
            System.out.println("No se pudieron cargar los nombres de las sucursales.");
        } else {
            System.out.println("Lista de nombres cargada correctamente: " + nombre);
        }

        JFrame frame = new JFrame("Sucursales");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(600, 400);

        jpCards jpCards = new jpCards(nombre);
        frame.add(new JScrollPane(jpCards)); 

        frame.setVisible(true);
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
